# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTg5MTE3ZTM0OWIzOWJiOGI2Y2Q0N2M2MGRkYjE0NzIxYmE5YzdmOTkxZjYzNTc4MWE4MDJiNTEyYTU3YzA1ZmRiYzE4N2ExNmVmMTFmNWY4OTIyOTYyZjE0NmU3MWIxMjNiNmYxNDRjMTY2ODFlMTgzMmVkY2JmYWJlZmRlY2Y=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
